{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNpGLY88qGg59JcrcoobsM2",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/QWERTYqwerty2323/Portfolio_Dashboard/blob/Main/NewUntiled.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "E0sItntNInwR"
      },
      "outputs": [],
      "source": [
        "# =============================================================================\n",
        "#  🇮🇳  3-YEAR INDIAN EQUITY PORTFOLIO DASHBOARD — STREAMLIT EDITION\n",
        "#\n",
        "#  Test locally / in Colab:   streamlit run app.py\n",
        "#  Deploy free:               https://share.streamlit.io  (point it at this repo,\n",
        "#                              main file = app.py)\n",
        "#\n",
        "#  Why this version is hardened against the \"app isn't running\" problem:\n",
        "#  Yahoo Finance often silently throttles or drops connections from cloud\n",
        "#  data-center IP ranges (AWS/GCP — which is what Streamlit Cloud runs on).\n",
        "#  Locally this usually errors out fast; on cloud infra it can instead just\n",
        "#  HANG with no error, which looks exactly like a stuck/dead app. Every\n",
        "#  network call below is wrapped in a hard wall-clock timeout via\n",
        "#  concurrent.futures, and all 15 tickers are fetched in PARALLEL at startup\n",
        "#  instead of one-by-one — so the absolute worst case is a few seconds slow,\n",
        "#  never an indefinite hang, and the app always finishes loading and renders\n",
        "#  something (live data, or the offline fallback figures) either way.\n",
        "# =============================================================================\n",
        "import warnings\n",
        "warnings.filterwarnings(\"ignore\")\n",
        "\n",
        "import concurrent.futures as cf\n",
        "from datetime import datetime, timedelta\n",
        "\n",
        "import pandas as pd\n",
        "import plotly.graph_objects as go\n",
        "import streamlit as st\n",
        "import yfinance as yf\n",
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# 0. PAGE CONFIG  (must be the very first Streamlit command in the script)\n",
        "# -----------------------------------------------------------------------------\n",
        "st.set_page_config(\n",
        "    page_title=\"Indian Equity Portfolio Dashboard\",\n",
        "    page_icon=\"🇮🇳\",\n",
        "    layout=\"wide\",\n",
        ")\n",
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# 1. CORE CONSTANTS\n",
        "# -----------------------------------------------------------------------------\n",
        "TOTAL_CAPITAL    = 1_00_00_000     # ₹1 Crore\n",
        "BROKERAGE_RATE   = 0.0025          # 0.25% on total volume (invested + current)\n",
        "STCG_RATE        = 0.20            # 20% on net positive gains after brokerage\n",
        "BENCHMARK        = \"^NSEI\"\n",
        "HOLDING_YEARS    = 3\n",
        "NETWORK_TIMEOUT  = 8                # hard cap, seconds, per external call\n",
        "PREFETCH_WORKERS = 8                # parallel fetch workers at startup\n",
        "\n",
        "\n",
        "def inr(x):\n",
        "    \"\"\"Format a number in Indian currency style: ₹#,##,###.##\"\"\"\n",
        "    try:\n",
        "        x = float(x)\n",
        "    except Exception:\n",
        "        return \"₹0.00\"\n",
        "    if x is None or pd.isna(x):\n",
        "        return \"-\"\n",
        "    neg = x < 0\n",
        "    x = abs(x)\n",
        "    s = f\"{x:,.2f}\"\n",
        "    int_part, dec_part = s.split(\".\")\n",
        "    int_part = int_part.replace(\",\", \"\")\n",
        "    if len(int_part) <= 3:\n",
        "        grouped = int_part\n",
        "    else:\n",
        "        last3, rest = int_part[-3:], int_part[:-3]\n",
        "        parts = []\n",
        "        while len(rest) > 2:\n",
        "            parts.insert(0, rest[-2:])\n",
        "            rest = rest[:-2]\n",
        "        if rest:\n",
        "            parts.insert(0, rest)\n",
        "        grouped = \",\".join(parts) + \",\" + last3\n",
        "    out = f\"₹{grouped}.{dec_part}\"\n",
        "    return f\"-{out}\" if neg else out\n",
        "\n",
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# 2. ASSET UNIVERSE, SECTORS, THESES\n",
        "# -----------------------------------------------------------------------------\n",
        "ASSET_META = {\n",
        "    \"10Y_GSEC\": {\"name\": \"10Y Indian G-Sec\", \"class\": \"Debt\",\n",
        "                 \"sector\": \"Sovereign Debt\", \"yield\": 0.07,\n",
        "                 \"thesis\": \"Risk-free sovereign anchor providing fixed 7% p.a. accrual, uncorrelated with equity drawdowns.\"},\n",
        "    \"AAA_BOND\": {\"name\": \"AAA Corporate Bond / Debenture\", \"class\": \"Debt\",\n",
        "                 \"sector\": \"Corporate Debt\", \"yield\": 0.08,\n",
        "                 \"thesis\": \"High-grade corporate debenture offering a modest credit-spread pick-up of 100bps over the G-Sec.\"},\n",
        "    \"GOLDBEES.NS\": {\"name\": \"Nippon India ETF Gold BeES\", \"class\": \"Gold\",\n",
        "                     \"sector\": \"Commodity\", \"yield\": 0.09,\n",
        "                     \"thesis\": \"Sovereign-backed gold ETF used as an inflation hedge and portfolio diversifier against equity/currency shocks.\"},\n",
        "\n",
        "    \"MARUTI.NS\":     {\"name\": \"Maruti Suzuki India Ltd\", \"class\": \"Equity\", \"sector\": \"Automobiles\",\n",
        "                       \"thesis\": \"India's largest passenger-vehicle maker; a defensive, low-beta compounder riding rural demand recovery and SUV mix upgrades.\"},\n",
        "    \"BAJAJ-AUTO.NS\": {\"name\": \"Bajaj Auto Ltd\", \"class\": \"Equity\", \"sector\": \"Automobiles\",\n",
        "                       \"thesis\": \"Two/three-wheeler leader with a strong export franchise and EV optionality via Chetak; quality-growth compounder with high payout.\"},\n",
        "    \"HAL.NS\":        {\"name\": \"Hindustan Aeronautics Ltd\", \"class\": \"Equity\", \"sector\": \"Defense / Capital Goods\",\n",
        "                       \"thesis\": \"Near-monopoly domestic defense-aircraft manufacturer benefiting from indigenization push and a record order backlog; high-beta momentum name.\"},\n",
        "    \"SIEMENS.NS\":    {\"name\": \"Siemens Ltd\", \"class\": \"Equity\", \"sector\": \"Capital Goods\",\n",
        "                       \"thesis\": \"Diversified industrial automation and electrification major positioned on India's capex and power-infrastructure upcycle.\"},\n",
        "    \"POLYCAB.NS\":    {\"name\": \"Polycab India Ltd\", \"class\": \"Equity\", \"sector\": \"Capital Goods / Manufacturing\",\n",
        "                       \"thesis\": \"Market-leading cables & wires manufacturer; steady compounder with an expanding FMEG (fans, appliances) distribution business.\"},\n",
        "    \"AXISBANK.NS\":   {\"name\": \"Axis Bank Ltd\", \"class\": \"Equity\", \"sector\": \"Financials\",\n",
        "                       \"thesis\": \"Private-sector bank in a valuation re-rating phase, supported by improving asset quality and retail-loan growth.\"},\n",
        "    \"BSE.NS\":        {\"name\": \"BSE Ltd\", \"class\": \"Equity\", \"sector\": \"Capital Markets\",\n",
        "                       \"thesis\": \"India's oldest stock exchange; a high-beta play on retail derivatives-trading volumes and market-infrastructure growth.\"},\n",
        "    \"HINDUNILVR.NS\": {\"name\": \"Hindustan Unilever Ltd\", \"class\": \"Equity\", \"sector\": \"FMCG\",\n",
        "                       \"thesis\": \"India's largest FMCG company; a low-beta defensive anchor with pricing power across home & personal-care categories.\"},\n",
        "    \"BRITANNIA.NS\":  {\"name\": \"Britannia Industries Ltd\", \"class\": \"Equity\", \"sector\": \"FMCG\",\n",
        "                       \"thesis\": \"Dominant biscuits & bakery player expanding into adjacent categories; defensive earnings visibility.\"},\n",
        "    \"ITC.NS\":        {\"name\": \"ITC Ltd\", \"class\": \"Equity\", \"sector\": \"FMCG\",\n",
        "                       \"thesis\": \"Diversified FMCG-cigarettes-agri-paper conglomerate; a defensive anchor with one of the highest dividend yields in the index.\"},\n",
        "    \"PIDILITIND.NS\": {\"name\": \"Pidilite Industries Ltd\", \"class\": \"Equity\", \"sector\": \"Chemicals\",\n",
        "                       \"thesis\": \"Dominant adhesives (Fevicol) franchise with pricing power over raw-material cycles; a steady structural compounder.\"},\n",
        "    \"SOLARINDS.NS\":  {\"name\": \"Solar Industries India Ltd\", \"class\": \"Equity\", \"sector\": \"Chemicals / Defense\",\n",
        "                       \"thesis\": \"Leading industrial-explosives maker with a fast-scaling defense ordnance order book; a high-beta aggressive-growth name.\"},\n",
        "}\n",
        "\n",
        "EQUITY_TICKERS = [t for t, m in ASSET_META.items() if m[\"class\"] == \"Equity\"]\n",
        "BOND_TICKERS   = [\"10Y_GSEC\", \"AAA_BOND\"]\n",
        "ALL_TICKERS    = list(ASSET_META.keys())\n",
        "YF_TICKERS     = [t for t in ALL_TICKERS if t not in BOND_TICKERS]\n",
        "\n",
        "INDUSTRY_AVG_PE = {\n",
        "    \"Automobiles\": 28.0, \"Defense / Capital Goods\": 40.0, \"Capital Goods\": 45.0,\n",
        "    \"Capital Goods / Manufacturing\": 42.0, \"Financials\": 20.0, \"Capital Markets\": 35.0,\n",
        "    \"FMCG\": 55.0, \"Chemicals\": 50.0, \"Chemicals / Defense\": 50.0,\n",
        "}\n",
        "\n",
        "SCENARIOS = {\n",
        "    \"Conservative (₹1.75 Cr)\": {\n",
        "        \"target\": 1_75_00_000,\n",
        "        \"weights\": {\"10Y_GSEC\": 10, \"AAA_BOND\": 7, \"GOLDBEES.NS\": 8,\n",
        "                    \"MARUTI.NS\": 7, \"BAJAJ-AUTO.NS\": 6, \"HAL.NS\": 9, \"SIEMENS.NS\": 8,\n",
        "                    \"POLYCAB.NS\": 11, \"AXISBANK.NS\": 5, \"BSE.NS\": 6, \"HINDUNILVR.NS\": 7,\n",
        "                    \"BRITANNIA.NS\": 4, \"ITC.NS\": 4, \"PIDILITIND.NS\": 3, \"SOLARINDS.NS\": 5},\n",
        "    },\n",
        "    \"Moderate (₹2.00 Cr)\": {\n",
        "        \"target\": 2_00_00_000,\n",
        "        \"weights\": {\"10Y_GSEC\": 5, \"AAA_BOND\": 4, \"GOLDBEES.NS\": 6,\n",
        "                    \"MARUTI.NS\": 4, \"BAJAJ-AUTO.NS\": 4, \"HAL.NS\": 15, \"SIEMENS.NS\": 9,\n",
        "                    \"POLYCAB.NS\": 11, \"AXISBANK.NS\": 6, \"BSE.NS\": 13, \"HINDUNILVR.NS\": 4,\n",
        "                    \"BRITANNIA.NS\": 3, \"ITC.NS\": 3, \"PIDILITIND.NS\": 3, \"SOLARINDS.NS\": 10},\n",
        "    },\n",
        "    \"Aggressive (₹2.25 Cr)\": {\n",
        "        \"target\": 2_25_00_000,\n",
        "        \"weights\": {\"10Y_GSEC\": 2, \"AAA_BOND\": 2, \"GOLDBEES.NS\": 3,\n",
        "                    \"MARUTI.NS\": 2, \"BAJAJ-AUTO.NS\": 2, \"HAL.NS\": 24, \"SIEMENS.NS\": 6,\n",
        "                    \"POLYCAB.NS\": 6, \"AXISBANK.NS\": 6, \"BSE.NS\": 20, \"HINDUNILVR.NS\": 3,\n",
        "                    \"BRITANNIA.NS\": 2, \"ITC.NS\": 3, \"PIDILITIND.NS\": 3, \"SOLARINDS.NS\": 16},\n",
        "    },\n",
        "}\n",
        "\n",
        "FALLBACK_DATA = {\n",
        "    \"MARUTI.NS\":     {\"cmp\": 12800.0, \"eps\": 440.0, \"pe\": 29.0, \"beta\": 0.85, \"mcap_cr\": 402000, \"low52\": 10500.0, \"high52\": 13700.0, \"buy_price\": 9200.0},\n",
        "    \"BAJAJ-AUTO.NS\": {\"cmp\": 9500.0,  \"eps\": 250.0, \"pe\": 38.0, \"beta\": 0.75, \"mcap_cr\": 265000, \"low52\": 7000.0,  \"high52\": 12800.0, \"buy_price\": 4300.0},\n",
        "    \"HAL.NS\":        {\"cmp\": 4800.0,  \"eps\": 105.0, \"pe\": 45.7, \"beta\": 1.20, \"mcap_cr\": 320000, \"low52\": 3200.0,  \"high52\": 5675.0,  \"buy_price\": 1450.0},\n",
        "    \"SIEMENS.NS\":    {\"cmp\": 6500.0,  \"eps\": 95.0,  \"pe\": 68.0, \"beta\": 1.05, \"mcap_cr\": 231000, \"low52\": 5200.0,  \"high52\": 8400.0,  \"buy_price\": 2600.0},\n",
        "    \"POLYCAB.NS\":    {\"cmp\": 6900.0,  \"eps\": 150.0, \"pe\": 46.0, \"beta\": 0.95, \"mcap_cr\": 104000, \"low52\": 4800.0,  \"high52\": 7600.0,  \"buy_price\": 2200.0},\n",
        "    \"AXISBANK.NS\":   {\"cmp\": 1180.0,  \"eps\": 78.0,  \"pe\": 15.1, \"beta\": 1.30, \"mcap_cr\": 365000, \"low52\": 950.0,   \"high52\": 1340.0,  \"buy_price\": 700.0},\n",
        "    \"BSE.NS\":        {\"cmp\": 5200.0,  \"eps\": 95.0,  \"pe\": 54.7, \"beta\": 1.60, \"mcap_cr\": 70000,  \"low52\": 1800.0,  \"high52\": 6100.0,  \"buy_price\": 350.0},\n",
        "    \"HINDUNILVR.NS\": {\"cmp\": 2500.0,  \"eps\": 43.0,  \"pe\": 58.1, \"beta\": 0.55, \"mcap_cr\": 588000, \"low52\": 2100.0,  \"high52\": 3035.0,  \"buy_price\": 2300.0},\n",
        "    \"BRITANNIA.NS\":  {\"cmp\": 5700.0,  \"eps\": 90.0,  \"pe\": 63.3, \"beta\": 0.60, \"mcap_cr\": 137000, \"low52\": 4500.0,  \"high52\": 6470.0,  \"buy_price\": 3400.0},\n",
        "    \"ITC.NS\":        {\"cmp\": 460.0,   \"eps\": 16.0,  \"pe\": 28.8, \"beta\": 0.65, \"mcap_cr\": 575000, \"low52\": 390.0,   \"high52\": 500.0,   \"buy_price\": 210.0},\n",
        "    \"PIDILITIND.NS\": {\"cmp\": 3100.0,  \"eps\": 45.0,  \"pe\": 68.9, \"beta\": 0.70, \"mcap_cr\": 157000, \"low52\": 2500.0,  \"high52\": 3400.0,  \"buy_price\": 1750.0},\n",
        "    \"SOLARINDS.NS\":  {\"cmp\": 12500.0, \"eps\": 180.0, \"pe\": 69.4, \"beta\": 1.55, \"mcap_cr\": 116000, \"low52\": 5900.0,  \"high52\": 13100.0, \"buy_price\": 1500.0},\n",
        "    \"GOLDBEES.NS\":   {\"cmp\": 72.0,    \"eps\": None,  \"pe\": None, \"beta\": 0.10, \"mcap_cr\": None,   \"low52\": 50.0,    \"high52\": 78.0,    \"buy_price\": 45.0},\n",
        "}\n",
        "\n",
        "\n",
        "def validate_scenarios():\n",
        "    problems = []\n",
        "    for name, sc in SCENARIOS.items():\n",
        "        total = sum(sc[\"weights\"].values())\n",
        "        if abs(total - 100) > 1e-6:\n",
        "            problems.append(f\"'{name}' weights sum to {total}, expected 100\")\n",
        "    return problems\n",
        "\n",
        "\n",
        "_config_problems = validate_scenarios()\n",
        "if _config_problems:\n",
        "    st.error(\"⚠️ Configuration error — fix SCENARIOS before this app can run:\\n\\n\" +\n",
        "              \"\\n\".join(f\"- {p}\" for p in _config_problems))\n",
        "    st.stop()\n",
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# 3. HARD-TIMEOUT NETWORK LAYER\n",
        "#    Every yfinance call is wrapped so it can NEVER hang the app: if Yahoo\n",
        "#    Finance is slow, throttled, or blocked, the call gives up after\n",
        "#    NETWORK_TIMEOUT seconds and the app falls back automatically.\n",
        "# -----------------------------------------------------------------------------\n",
        "def _bounded(fn, timeout=NETWORK_TIMEOUT):\n",
        "    \"\"\"Run fn() with a hard wall-clock timeout. Returns None on any failure or timeout.\"\"\"\n",
        "    try:\n",
        "        with cf.ThreadPoolExecutor(max_workers=1) as ex:\n",
        "            fut = ex.submit(fn)\n",
        "            return fut.result(timeout=timeout)\n",
        "    except Exception:\n",
        "        return None\n",
        "\n",
        "\n",
        "@st.cache_data(ttl=3600, show_spinner=False)\n",
        "def fetch_history(ticker, period=\"5y\"):\n",
        "    def _do():\n",
        "        df = yf.Ticker(ticker).history(period=period, auto_adjust=True, timeout=NETWORK_TIMEOUT)\n",
        "        return df if df is not None and not df.empty else None\n",
        "    return _bounded(_do)\n",
        "\n",
        "\n",
        "@st.cache_data(ttl=3600, show_spinner=False)\n",
        "def fetch_info(ticker):\n",
        "    def _do():\n",
        "        info = yf.Ticker(ticker).info\n",
        "        return info if isinstance(info, dict) else {}\n",
        "    return _bounded(_do, timeout=6) or {}\n",
        "\n",
        "\n",
        "@st.cache_resource(show_spinner=False)\n",
        "def prefetch_market_data():\n",
        "    \"\"\"Warm the cache for every ticker IN PARALLEL, once per hour, so a\n",
        "    single slow/blocked ticker can never delay the others. Sequential\n",
        "    fetching of 15 tickers at up to 8s each could take 2 minutes; this\n",
        "    bounds the whole batch to roughly one timeout window.\"\"\"\n",
        "    tickers = YF_TICKERS + [BENCHMARK]\n",
        "    with cf.ThreadPoolExecutor(max_workers=PREFETCH_WORKERS) as ex:\n",
        "        list(ex.map(fetch_history, tickers))\n",
        "        list(ex.map(fetch_info, YF_TICKERS))\n",
        "    return True\n",
        "\n",
        "\n",
        "with st.spinner(\"Fetching live NSE market data (falls back automatically if Yahoo Finance is unreachable)...\"):\n",
        "    prefetch_market_data()\n",
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# 4. PRICE / BETA / ENTRY-DATE HELPERS\n",
        "# -----------------------------------------------------------------------------\n",
        "def get_entry_date(hist):\n",
        "    if hist is None or hist.empty:\n",
        "        return None\n",
        "    target = pd.Timestamp(datetime.now() - timedelta(days=365 * HOLDING_YEARS))\n",
        "    idx = hist.index\n",
        "    if idx.tz is not None and target.tzinfo is None:\n",
        "        target = target.tz_localize(idx.tz)\n",
        "    pos = idx.get_indexer([target], method=\"nearest\")[0]\n",
        "    return idx[pos]\n",
        "\n",
        "\n",
        "def compute_beta_vs_nifty(hist):\n",
        "    try:\n",
        "        nifty_hist = fetch_history(BENCHMARK)\n",
        "        if nifty_hist is None or nifty_hist.empty or hist is None:\n",
        "            return None\n",
        "        s_ret = hist[\"Close\"].pct_change().dropna()\n",
        "        n_ret = nifty_hist[\"Close\"].pct_change().dropna()\n",
        "        joined = pd.concat([s_ret, n_ret], axis=1, join=\"inner\")\n",
        "        joined.columns = [\"s\", \"n\"]\n",
        "        if len(joined) < 30:\n",
        "            return None\n",
        "        var = joined[\"n\"].var()\n",
        "        return float(joined[\"s\"].cov(joined[\"n\"]) / var) if var > 0 else None\n",
        "    except Exception:\n",
        "        return None\n",
        "\n",
        "\n",
        "def get_price_series(t):\n",
        "    hist, info = fetch_history(t), fetch_info(t)\n",
        "    fb = FALLBACK_DATA.get(t, {})\n",
        "    live = hist is not None and len(hist) > 5\n",
        "\n",
        "    if live:\n",
        "        cmp_ = float(hist[\"Close\"].iloc[-1])\n",
        "        entry_date = get_entry_date(hist)\n",
        "        buy_price = float(hist.loc[entry_date, \"Close\"]) if entry_date is not None else float(hist[\"Close\"].iloc[0])\n",
        "        beta = info.get(\"beta\") or compute_beta_vs_nifty(hist) or fb.get(\"beta\", 1.0)\n",
        "        low52 = float(hist[\"Close\"].tail(252).min())\n",
        "        high52 = float(hist[\"Close\"].tail(252).max())\n",
        "    else:\n",
        "        cmp_ = fb.get(\"cmp\", 100.0)\n",
        "        buy_price = fb.get(\"buy_price\", cmp_ * 0.6)\n",
        "        beta = fb.get(\"beta\", 1.0)\n",
        "        low52 = fb.get(\"low52\", cmp_ * 0.8)\n",
        "        high52 = fb.get(\"high52\", cmp_ * 1.2)\n",
        "\n",
        "    return {\"cmp\": cmp_, \"buy_price\": buy_price, \"beta\": beta,\n",
        "            \"low52\": low52, \"high52\": high52, \"live\": live, \"info\": info}\n",
        "\n",
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# 5. SCENARIO PORTFOLIO ENGINE\n",
        "# -----------------------------------------------------------------------------\n",
        "@st.cache_data(ttl=3600, show_spinner=False)\n",
        "def compute_scenario(scenario_name):\n",
        "    sc = SCENARIOS[scenario_name]\n",
        "    rows = []\n",
        "    for t, w_pct in sc[\"weights\"].items():\n",
        "        meta = ASSET_META[t]\n",
        "        allocated = TOTAL_CAPITAL * w_pct / 100.0\n",
        "\n",
        "        if meta[\"class\"] == \"Debt\":\n",
        "            invested = allocated\n",
        "            current_value = invested * ((1 + meta[\"yield\"]) ** HOLDING_YEARS)\n",
        "            qty = buy_price = cmp_ = None\n",
        "            beta = 0.0\n",
        "        else:\n",
        "            p = get_price_series(t)\n",
        "            buy_price, cmp_, beta = p[\"buy_price\"], p[\"cmp\"], p[\"beta\"]\n",
        "            qty = int(allocated / buy_price) if buy_price and buy_price > 0 else 0\n",
        "            invested = qty * buy_price\n",
        "            current_value = qty * cmp_\n",
        "            leftover = allocated - invested\n",
        "            invested += leftover\n",
        "            current_value += leftover\n",
        "\n",
        "        gross_profit = current_value - invested\n",
        "        brokerage = BROKERAGE_RATE * (invested + current_value)\n",
        "        taxable_gain = max(gross_profit - brokerage, 0)\n",
        "        stcg = STCG_RATE * taxable_gain\n",
        "        net_profit = gross_profit - brokerage - stcg\n",
        "        cagr = (current_value / invested) ** (1 / HOLDING_YEARS) - 1 if invested > 0 else 0.0\n",
        "\n",
        "        rows.append({\n",
        "            \"ticker\": t, \"name\": meta[\"name\"], \"class\": meta[\"class\"], \"sector\": meta.get(\"sector\", \"\"),\n",
        "            \"weight_pct\": w_pct, \"allocated\": allocated, \"qty\": qty, \"buy_price\": buy_price, \"cmp\": cmp_,\n",
        "            \"invested\": invested, \"current_value\": current_value, \"gross_profit\": gross_profit,\n",
        "            \"brokerage\": brokerage, \"stcg\": stcg, \"net_profit\": net_profit, \"beta\": beta, \"cagr\": cagr,\n",
        "        })\n",
        "\n",
        "    df = pd.DataFrame(rows)\n",
        "    inv_sum, cur_sum = df[\"invested\"].sum(), df[\"current_value\"].sum()\n",
        "    kpis = {\n",
        "        \"current_value\": cur_sum, \"invested\": inv_sum,\n",
        "        \"gross_profit\": df[\"gross_profit\"].sum(), \"brokerage\": df[\"brokerage\"].sum(),\n",
        "        \"stcg\": df[\"stcg\"].sum(), \"net_profit\": df[\"net_profit\"].sum(),\n",
        "        \"net_return_pct\": (cur_sum / inv_sum - 1) * 100 if inv_sum else 0.0,\n",
        "        \"weighted_beta\": (df[\"weight_pct\"] / 100 * df[\"beta\"]).sum(),\n",
        "        \"target\": sc[\"target\"],\n",
        "    }\n",
        "    return df, kpis\n",
        "\n",
        "\n",
        "@st.cache_data(ttl=3600, show_spinner=False)\n",
        "def get_nifty_norm():\n",
        "    close_hist = fetch_history(BENCHMARK)\n",
        "    if close_hist is None or close_hist.empty:\n",
        "        return None\n",
        "    close = close_hist[\"Close\"]\n",
        "    return close / close.iloc[0] * 100\n",
        "\n",
        "\n",
        "@st.cache_data(ttl=3600, show_spinner=False)\n",
        "def build_portfolio_index_series(scenario_name):\n",
        "    nifty_hist = fetch_history(BENCHMARK)\n",
        "    if nifty_hist is None or nifty_hist.empty:\n",
        "        return None\n",
        "\n",
        "    weights = SCENARIOS[scenario_name][\"weights\"]\n",
        "    master_idx = nifty_hist.index\n",
        "    days = (master_idx - master_idx[0]).days.values\n",
        "\n",
        "    portfolio_rel = pd.Series(0.0, index=master_idx)\n",
        "    for t, w_pct in weights.items():\n",
        "        meta = ASSET_META[t]\n",
        "        w = w_pct / 100.0\n",
        "        if meta[\"class\"] == \"Debt\":\n",
        "            rel = pd.Series((1 + meta[\"yield\"]) ** (days / 365.0), index=master_idx)\n",
        "        else:\n",
        "            hist = fetch_history(t)\n",
        "            if hist is not None and not hist.empty:\n",
        "                s = hist[\"Close\"].reindex(master_idx, method=\"ffill\").bfill()\n",
        "                rel = s / s.iloc[0]\n",
        "            else:\n",
        "                fb_cagr = 0.15\n",
        "                rel = pd.Series((1 + fb_cagr) ** (days / 365.0), index=master_idx)\n",
        "        portfolio_rel = portfolio_rel.add(rel * w, fill_value=0)\n",
        "\n",
        "    return portfolio_rel * 100\n",
        "\n",
        "\n",
        "def valuation_status(pe, sector):\n",
        "    avg = INDUSTRY_AVG_PE.get(sector)\n",
        "    if pe is None or avg is None:\n",
        "        return \"N/A\"\n",
        "    diff = (pe - avg) / avg\n",
        "    if diff > 0.15:\n",
        "        return f\"Overvalued vs {sector} avg ({avg:.1f}x)\"\n",
        "    if diff < -0.15:\n",
        "        return f\"Undervalued vs {sector} avg ({avg:.1f}x)\"\n",
        "    return f\"Fairly valued vs {sector} avg ({avg:.1f}x)\"\n",
        "\n",
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# 6. CHART BUILDERS\n",
        "# -----------------------------------------------------------------------------\n",
        "CLASS_ORDER = [\"Equity\", \"Debt\", \"Gold\"]\n",
        "CLASS_COLORS = [\"#1a73e8\", \"#5f6368\", \"#fbbc04\"]\n",
        "\n",
        "\n",
        "def build_donut(df, scenario_name):\n",
        "    grp = df.groupby(\"class\")[\"current_value\"].sum().reindex(CLASS_ORDER).fillna(0)\n",
        "    fig = go.Figure(go.Pie(labels=grp.index, values=grp.values, hole=0.55,\n",
        "                            marker=dict(colors=CLASS_COLORS)))\n",
        "    fig.update_layout(title=f\"Asset Class Allocation — {scenario_name}\", height=380,\n",
        "                       template=\"plotly_white\", legend=dict(orientation=\"h\", y=-0.15),\n",
        "                       margin=dict(t=60, b=40))\n",
        "    return fig\n",
        "\n",
        "\n",
        "def build_bar(df, scenario_name):\n",
        "    d = df.sort_values(\"net_profit\")\n",
        "    colors = [\"#188038\" if v >= 0 else \"#d93025\" for v in d[\"net_profit\"]]\n",
        "    fig = go.Figure(go.Bar(x=d[\"net_profit\"], y=d[\"name\"], orientation=\"h\", marker_color=colors,\n",
        "                            text=[inr(v) for v in d[\"net_profit\"]], textposition=\"outside\"))\n",
        "    fig.update_layout(title=f\"Asset-wise Net Profit / Loss — {scenario_name}\", height=520,\n",
        "                       template=\"plotly_white\", margin=dict(l=190, t=60))\n",
        "    return fig\n",
        "\n",
        "\n",
        "def build_line(scenario_name):\n",
        "    port_idx = build_portfolio_index_series(scenario_name)\n",
        "    nifty_norm = get_nifty_norm()\n",
        "    fig = go.Figure()\n",
        "    if port_idx is not None and nifty_norm is not None:\n",
        "        fig.add_trace(go.Scatter(x=port_idx.index, y=port_idx.values, mode=\"lines\",\n",
        "                                  name=\"Portfolio\", line=dict(color=\"#1a73e8\", width=2)))\n",
        "        fig.add_trace(go.Scatter(x=nifty_norm.index, y=nifty_norm.values, mode=\"lines\",\n",
        "                                  name=\"Nifty 50\", line=dict(color=\"#e37400\", width=2, dash=\"dot\")))\n",
        "    else:\n",
        "        fig.add_annotation(text=\"Benchmark history unavailable — Nifty 50 data could not be fetched\",\n",
        "                            showarrow=False)\n",
        "    fig.update_layout(title=f\"5-Year Normalized Return: Portfolio vs Nifty 50 (Base = ₹100) — {scenario_name}\",\n",
        "                       template=\"plotly_white\", height=420, xaxis_title=\"Date\", yaxis_title=\"Indexed Value\")\n",
        "    return fig\n",
        "\n",
        "\n",
        "def build_dma_chart(ticker):\n",
        "    meta = ASSET_META[ticker]\n",
        "    hist = fetch_history(ticker)\n",
        "    fig = go.Figure()\n",
        "    if hist is not None and not hist.empty:\n",
        "        dma50, dma200 = hist[\"Close\"].rolling(50).mean(), hist[\"Close\"].rolling(200).mean()\n",
        "        fig.add_trace(go.Scatter(x=hist.index, y=hist[\"Close\"], name=\"Close\", line=dict(color=\"#1a73e8\")))\n",
        "        fig.add_trace(go.Scatter(x=hist.index, y=dma50, name=\"50 DMA\", line=dict(color=\"#e37400\", width=1.3)))\n",
        "        fig.add_trace(go.Scatter(x=hist.index, y=dma200, name=\"200 DMA\", line=dict(color=\"#d93025\", width=1.3)))\n",
        "    else:\n",
        "        fig.add_annotation(text=\"5-year chart unavailable — offline fallback mode\", showarrow=False)\n",
        "    fig.update_layout(title=f\"{meta['name']} — 5-Year Price with 50/200 DMA\", template=\"plotly_white\",\n",
        "                       height=430, xaxis=dict(rangeslider=dict(visible=True)))\n",
        "    return fig\n",
        "\n",
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# 7. UI — HEADER + DATA-SOURCE STATUS\n",
        "# -----------------------------------------------------------------------------\n",
        "st.title(\"🇮🇳 3-Year Indian Equity Portfolio Dashboard\")\n",
        "st.caption(\"₹1 Crore capital · 15-asset universe · 3-year multi-scenario terminal-value model\")\n",
        "\n",
        "with st.expander(\"📡 Data source status (tap to check live vs. offline-fallback)\"):\n",
        "    live_flags = {t: (fetch_history(t) is not None) for t in YF_TICKERS}\n",
        "    live_count = sum(live_flags.values())\n",
        "    st.caption(f\"{live_count} / {len(live_flags)} tickers on live Yahoo Finance data. \"\n",
        "               f\"The rest are using built-in offline fallback fundamentals — the dashboard \"\n",
        "               f\"still works normally either way, figures are just less current.\")\n",
        "    status_cols = st.columns(4)\n",
        "    for i, (t, ok) in enumerate(live_flags.items()):\n",
        "        status_cols[i % 4].write(f\"{'🟢' if ok else '🟡'} {ASSET_META[t]['name']}\")\n",
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# 8. UI — SCENARIO BUTTONS  (st.session_state keeps the selection across reruns)\n",
        "# -----------------------------------------------------------------------------\n",
        "if \"scenario\" not in st.session_state:\n",
        "    st.session_state.scenario = list(SCENARIOS.keys())[0]\n",
        "\n",
        "btn_cols = st.columns(3)\n",
        "for col, name in zip(btn_cols, SCENARIOS.keys()):\n",
        "    with col:\n",
        "        if st.button(\n",
        "            name,\n",
        "            width=\"stretch\",\n",
        "            type=\"primary\" if st.session_state.scenario == name else \"secondary\",\n",
        "            key=f\"btn_{name}\",\n",
        "        ):\n",
        "            st.session_state.scenario = name\n",
        "            st.rerun()\n",
        "\n",
        "scenario_name = st.session_state.scenario\n",
        "\n",
        "try:\n",
        "    df, kpis = compute_scenario(scenario_name)\n",
        "\n",
        "    st.markdown(f\"**Showing:** {scenario_name}\")\n",
        "\n",
        "    # ---- KPI cards -----------------------------------------------------\n",
        "    k1, k2, k3, k4 = st.columns(4)\n",
        "    k1.metric(\"Current Portfolio Value\", inr(kpis[\"current_value\"]))\n",
        "    k2.metric(\"Total Invested\", inr(kpis[\"invested\"]))\n",
        "    k3.metric(\"Gross Profit\", inr(kpis[\"gross_profit\"]))\n",
        "    k4.metric(\"Total Brokerage\", inr(kpis[\"brokerage\"]))\n",
        "\n",
        "    k5, k6, k7, k8 = st.columns(4)\n",
        "    k5.metric(\"Estimated STCG Tax (20%)\", inr(kpis[\"stcg\"]))\n",
        "    k6.metric(\"Net Take-Home Profit\", inr(kpis[\"net_profit\"]))\n",
        "    k7.metric(\"Net Portfolio Return\", f\"{kpis['net_return_pct']:.2f}%\")\n",
        "    k8.metric(\"Weighted Portfolio Beta\", f\"{kpis['weighted_beta']:.2f}\")\n",
        "\n",
        "    gap = kpis[\"target\"] - kpis[\"current_value\"]\n",
        "    if gap <= 0:\n",
        "        st.success(f\"3-Year Target {inr(kpis['target'])} — achieved / exceeded ✅\")\n",
        "    else:\n",
        "        st.warning(f\"3-Year Target {inr(kpis['target'])} — shortfall of {inr(gap)}\")\n",
        "\n",
        "    # ---- Charts ----------------------------------------------------------\n",
        "    c1, c2 = st.columns([1, 1.4])\n",
        "    with c1:\n",
        "        st.plotly_chart(build_donut(df, scenario_name), width=\"stretch\")\n",
        "    with c2:\n",
        "        st.plotly_chart(build_bar(df, scenario_name), width=\"stretch\")\n",
        "\n",
        "    st.plotly_chart(build_line(scenario_name), width=\"stretch\")\n",
        "\n",
        "    # ---- Holdings table ----------------------------------------------------\n",
        "    st.subheader(\"Holdings Detail\")\n",
        "    show = df.copy()\n",
        "    show[\"Weight %\"] = show[\"weight_pct\"].map(lambda v: f\"{v:.1f}%\")\n",
        "    show[\"Allocated\"] = show[\"allocated\"].map(inr)\n",
        "    show[\"Qty\"] = show[\"qty\"].map(lambda v: \"-\" if v is None or pd.isna(v) else f\"{int(v):,}\")\n",
        "    show[\"Buy Price\"] = show[\"buy_price\"].map(lambda v: \"-\" if v is None or pd.isna(v) else inr(v))\n",
        "    show[\"CMP\"] = show[\"cmp\"].map(lambda v: \"-\" if v is None or pd.isna(v) else inr(v))\n",
        "    show[\"Current Value\"] = show[\"current_value\"].map(inr)\n",
        "    show[\"Net Profit\"] = show[\"net_profit\"].map(inr)\n",
        "    show[\"CAGR\"] = show[\"cagr\"].map(lambda v: f\"{v * 100:.2f}%\")\n",
        "    show[\"Beta\"] = show[\"beta\"].map(lambda v: f\"{v:.2f}\")\n",
        "    cols = [\"name\", \"class\", \"Weight %\", \"Allocated\", \"Qty\", \"Buy Price\", \"CMP\",\n",
        "            \"Current Value\", \"Net Profit\", \"CAGR\", \"Beta\"]\n",
        "    st.dataframe(show[cols].rename(columns={\"name\": \"Asset\", \"class\": \"Class\"}),\n",
        "                 width=\"stretch\", hide_index=True)\n",
        "\n",
        "except Exception as e:\n",
        "    st.error(\"Something went wrong rendering the scenario dashboard. Details below:\")\n",
        "    st.exception(e)\n",
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# 9. UI — COMPANY DEEP-DIVE SCREENER\n",
        "# -----------------------------------------------------------------------------\n",
        "st.divider()\n",
        "st.header(\"🔎 Company Deep-Dive Screener\")\n",
        "\n",
        "try:\n",
        "    ticker = st.selectbox(\n",
        "        \"Select Company\",\n",
        "        options=EQUITY_TICKERS,\n",
        "        format_func=lambda t: ASSET_META[t][\"name\"],\n",
        "    )\n",
        "\n",
        "    meta = ASSET_META[ticker]\n",
        "    p = get_price_series(ticker)\n",
        "    info, fb = p[\"info\"], FALLBACK_DATA.get(ticker, {})\n",
        "    cmp_, hist = p[\"cmp\"], fetch_history(ticker)\n",
        "\n",
        "    pe = info.get(\"trailingPE\") or fb.get(\"pe\")\n",
        "    eps = info.get(\"trailingEps\") or fb.get(\"eps\")\n",
        "    mcap = info.get(\"marketCap\")\n",
        "    mcap_cr = (mcap / 1e7) if mcap else fb.get(\"mcap_cr\")\n",
        "    beta = p[\"beta\"]\n",
        "    low52 = info.get(\"fiftyTwoWeekLow\") or p[\"low52\"]\n",
        "    high52 = info.get(\"fiftyTwoWeekHigh\") or p[\"high52\"]\n",
        "\n",
        "    if hist is not None and not hist.empty and len(hist) > 1:\n",
        "        day_change_pct = (cmp_ - float(hist[\"Close\"].iloc[-2])) / float(hist[\"Close\"].iloc[-2]) * 100\n",
        "    else:\n",
        "        day_change_pct = 0.0\n",
        "\n",
        "    st.subheader(f\"{meta['name']} ({ticker})\")\n",
        "    st.caption(f\"{meta['sector']} — {'Live Data' if p['live'] else '⚠ Offline Fallback Data'}\")\n",
        "\n",
        "    d1, d2, d3, d4 = st.columns(4)\n",
        "    d1.metric(\"CMP\", inr(cmp_), f\"{day_change_pct:+.2f}% today\")\n",
        "    d2.metric(\"Market Cap\", (\"₹\" + format(mcap_cr, \",.0f\") + \" Cr\") if mcap_cr else \"N/A\")\n",
        "    d3.metric(\"Trailing P/E\", f\"{pe:.1f}x\" if pe else \"N/A\")\n",
        "    d4.metric(\"Beta\", f\"{beta:.2f}\")\n",
        "\n",
        "    d5, d6 = st.columns(2)\n",
        "    d5.metric(\"Trailing EPS\", f\"₹{eps:.2f}\" if eps else \"N/A\")\n",
        "    d6.metric(\"52W Range\", f\"{inr(low52)} – {inr(high52)}\")\n",
        "\n",
        "    st.markdown(f\"**Valuation Status:** {valuation_status(pe, meta['sector'])}\")\n",
        "    st.markdown(meta[\"thesis\"])\n",
        "\n",
        "    st.plotly_chart(build_dma_chart(ticker), width=\"stretch\")\n",
        "\n",
        "except Exception as e:\n",
        "    st.error(\"Something went wrong rendering the company screener. Details below:\")\n",
        "    st.exception(e)"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "streamlit>=1.38\n",
        "yfinance>=0.2.40\n",
        "pandas>=2.0\n",
        "numpy>=1.24\n",
        "plotly>=5.20"
      ],
      "metadata": {
        "id": "VFBLl342I_-G"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}